### PR TITLE
Added support node name

### PR DESCRIPTION
**Pull request by RaymondMouthaan**
Added support for node name instead of ip address, based upon the changes made by @lukasmalkmus regarding text collector.

### CODE REVIEW

**Comment by carlosedp** [comment]
Hey @RaymondMouthaan , can you remove .travis.yml from the PR since it's pointing to your DockerHub repository?

**Comment by RaymondMouthaan** [comment]
Sorry for that, is it gone now?

**Comment by carlosedp** [comment]
Actually now the whole file was deleted and not just removed from the PR.

**Comment by RaymondMouthaan** [comment]
Oeps, I still need to get used to PR stuff 

Recreated .travis.yml based upon yours.

**Pull request merged**
